### ISSUE TITLE
Tried to Read from Address Zero when removing magazines

### ISSUE THREAD

**Issue by Mohl97** [HDest-Community/Dimensional-Storage-Device#1]
It seems removing any magazine from the DSD causes the game to crash, I tested with a liberator mag and a napalm tank from Bangers And Mash, as those were the only mags I had on me at the time.
[log.txt](https://github.com/HDest-Community/Dimensional-Storage-Device/files/11620824/log.txt)

**Comment by Cryomundus** [comment]
Should be fixed now!
